kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rancher-pv-claim
  namespace: monitoring
spec:
  storageClassName: rancher-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

